# Ant1 + larger batch size
behaviors:
  Ant:
    trainer_type: poca
    hyperparameters:
      batch_size: 10248
      buffer_size: 65534
      learning_rate: 3.0e-4
      beta: 5.0e-4
      epsilon: 0.2
      lambd: 0.99
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 128
      num_layers: 4
      goal_conditioning_type: none
      conditioning_type: none
    max_steps: 1.0e+8
    time_horizon: 256
    summary_freq: 50000
    keep_checkpoints: 10
    checkpoint_interval: 1000000
    