behaviors:
  Ant:
    trainer_type: ppo
    hyperparameters:
      batch_size: 100
      buffer_size: 20000
      learning_rate: 3.0e-4
      beta: 5.0e-4
      epsilon: 0.2
      lambd: 0.99
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 2
      goal_conditioning_type: none
      conditioning_type: none   
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
        network_settings:
          normalize: false
          hidden_units: 256
          num_layers: 2
          vis_encode_type: simple       
          goal_conditioning_type: none       
    max_steps: 1.0e+8
    time_horizon: 10000
    summary_freq: 10000
    keep_checkpoints: 2
    checkpoint_interval: 500000
environment_parameters:
  curriculum_option:
    curriculum:
      - name: Lesson0 # This is the start of the second lesson
        completion_criteria:
          measure: reward
          behavior: Ant
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 1.5
        value: 0
      - name: Lesson1
        completion_criteria:
          measure: reward
          behavior: Ant
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 1.8
        value: 1
      - name: Lesson2
        completion_criteria:
          measure: reward
          behavior: Ant
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 1.8
        value: 2
