behaviors:
  Ant:
    trainer_type: ppo
    hyperparameters:
      batch_size: 10
      buffer_size: 20000
      learning_rate: 3.0e-4
      beta: 5.0e-4
      epsilon: 0.2
      lambd: 0.99
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 2
      goal_conditioning_type: hyper
      conditioning_type: hyper
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
        network_settings:
          normalize: false
          hidden_units: 256
          num_layers: 2
          vis_encode_type: simple       
          goal_conditioning_type: hyper
    max_steps: 1.0e+8
    time_horizon: 100
    summary_freq: 10000
    keep_checkpoints: 2
    checkpoint_interval: 500000
