behaviors:
  Ant:
    trainer_type: poca
    hyperparameters:
      batch_size: 256
      buffer_size: 12800
      learning_rate: 3.0e-4
      beta: 5.0e-4
      epsilon: 0.2
      lambd: 0.99
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 128
      num_layers: 4
      goal_conditioning_type: none
      conditioning_type: none
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
        network_settings:
          normalize: false
          hidden_units: 128
          num_layers: 4
          goal_conditioning_type: none
          conditioning_type: none 
    max_steps: 1.0e+8
    time_horizon: 1024
    summary_freq: 50000
    keep_checkpoints: 3
    checkpoint_interval: 500000
    